// src/export/kbExporter.ts
// Feature 23 — KB Entry Markdown Exporter

import * as fs from 'fs';
import * as path from 'path';
import type { KbEntry } from '../types/kb';
import { DEFAULT_KB_TYPES } from '../types/kb';

/**
 * Map from KB entry type to its output subdirectory name.
 * For custom types, the type name is used as-is (lowercased).
 */
function getTypeDir(type: string): string {
    const known: Record<string, string> = {
        decision:     'decisions',
        learning:     'learnings',
        pattern:      'patterns',
        gotcha:       'gotchas',
        architecture: 'architecture',
    };
    return known[type] ?? type.toLowerCase().replace(/\s+/g, '-');
}

/**
 * Parse the YAML frontmatter `locked` field from an existing KB entry file.
 * Returns true only when the file starts with `---` and contains `locked: true`.
 */
function isLockedFile(filePath: string): boolean {
    try {
        const content = fs.readFileSync(filePath, 'utf8');
        if (!content.startsWith('---')) { return false; }
        const frontmatterEnd = content.indexOf('\n---', 3);
        if (frontmatterEnd === -1) { return false; }
        const frontmatter = content.slice(3, frontmatterEnd);
        return /^\s*locked\s*:\s*true\s*$/m.test(frontmatter);
    } catch {
        return false;
    }
}

/**
 * Render a KB entry as an Obsidian-compatible Markdown file with YAML frontmatter.
 */
function renderEntryMarkdown(entry: KbEntry): string {
    const tagsYaml = entry.tags.length > 0
        ? `[${entry.tags.map(t => `${t}`).join(', ')}]`
        : '[]';

    return [
        '---',
        `sessionId: ${entry.sessionId}`,
        `type: ${entry.type}`,
        `tags: ${tagsYaml}`,
        `createdAt: ${entry.createdAt}`,
        `locked: ${entry.locked === true ? 'true' : 'false'}`,
        '---',
        `# ${entry.title}`,
        '',
        entry.summary,
        '',
        '---',
        `_Source: ChatWizard session · [Open in VS Code](vscode://chatwizard/session/${entry.sessionId})_`,
        '',
    ].join('\n');
}

/**
 * Build the index.md table of contents for all entries.
 */
function renderIndexMarkdown(
    entries: KbEntry[],
    clusters: Map<string, KbEntry[]>
): string {
    const lines: string[] = [
        '# ChatWizard Knowledge Base',
        '',
        `_Generated by ChatWizard · ${new Date().toISOString().slice(0, 10)}_`,
        '',
        `**Total entries:** ${entries.length}`,
        '',
        '## Table of Contents',
        '',
    ];

    // Group by type for the ToC
    const byType = new Map<string, KbEntry[]>();
    for (const entry of entries) {
        const arr = byType.get(entry.type) ?? [];
        arr.push(entry);
        byType.set(entry.type, arr);
    }

    // Order: known types first, then custom types alphabetically
    const presentTypes = new Set(byType.keys());
    const knownTypes = DEFAULT_KB_TYPES.filter(t => presentTypes.has(t));
    const customTypes = Array.from(presentTypes)
        .filter(t => !DEFAULT_KB_TYPES.includes(t))
        .sort();
    const typeOrder = [...knownTypes, ...customTypes];

    for (const type of typeOrder) {
        const typeEntries = byType.get(type);
        if (!typeEntries || typeEntries.length === 0) { continue; }

        const label = capitalise(type) + (DEFAULT_KB_TYPES.includes(type) ? 's' : '');
        lines.push(`### ${label} (${typeEntries.length})`);
        lines.push('');
        for (const entry of typeEntries) {
            const dir = getTypeDir(type);
            lines.push(`- [[${dir}/${entry.sessionId}|${entry.title}]]`);
        }
        lines.push('');
    }

    // Clusters section
    if (clusters.size > 0) {
        lines.push('## Clusters');
        lines.push('');
        for (const [clusterId, clusterEntries] of clusters.entries()) {
            lines.push(`### ${clusterId} (${clusterEntries.length})`);
            for (const entry of clusterEntries) {
                lines.push(`- ${entry.title}`);
            }
            lines.push('');
        }
    }

    return lines.join('\n');
}

function capitalise(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
}

export interface KbExportOptions {
    /** When true, skip files that already exist with `locked: true` in their frontmatter */
    incrementalUpdate: boolean;
}

/**
 * Export a set of KB entries as an Obsidian-compatible Markdown knowledge base.
 *
 * Output structure:
 * ```
 * <outputDir>/
 *   index.md              — table of contents
 *   decisions/<id>.md
 *   learnings/<id>.md
 *   patterns/<id>.md
 *   gotchas/<id>.md
 *   architecture/<id>.md
 * ```
 *
 * Incremental update: files with `locked: true` in their YAML frontmatter are
 * never overwritten.
 */
export async function exportKbAsync(
    entries: KbEntry[],
    clusters: Map<string, KbEntry[]>,
    outputDir: string,
    options: KbExportOptions
): Promise<void> {
    // Ensure output directory and type subdirectories exist
    await fs.promises.mkdir(outputDir, { recursive: true });
    const typeDirs = new Set(entries.map(e => getTypeDir(e.type)));
    for (const dir of typeDirs) {
        await fs.promises.mkdir(path.join(outputDir, dir), { recursive: true });
    }

    // Write individual entry files
    for (const entry of entries) {
        const dir = getTypeDir(entry.type);
        const filePath = path.join(outputDir, dir, `${entry.sessionId}.md`);

        // In incremental mode, skip locked files
        if (options.incrementalUpdate && isLockedFile(filePath)) {
            continue;
        }

        const content = renderEntryMarkdown(entry);
        await fs.promises.writeFile(filePath, content, 'utf8');
    }

    // Write index.md
    const indexPath = path.join(outputDir, 'index.md');
    const indexContent = renderIndexMarkdown(entries, clusters);
    await fs.promises.writeFile(indexPath, indexContent, 'utf8');
}