// src/mcp/mcpServer.ts
import * as fs from 'fs';
import * as http from 'http';
import * as path from 'path';
import { Server as SdkServer } from '@modelcontextprotocol/sdk/server/index.js';
import { SSEServerTransport } from '@modelcontextprotocol/sdk/server/sse.js';
import { ListToolsRequestSchema, CallToolRequestSchema, ListPromptsRequestSchema, GetPromptRequestSchema } from '@modelcontextprotocol/sdk/types.js';
import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import type { IMcpServer, IMcpTool, IMcpPrompt } from './mcpContracts';
import type { McpServerConfig } from '../types/index';

/**
 * Implements the IMcpServer lifecycle contract.
 *
 * Starts a local HTTP/SSE server bound to 127.0.0.1 only.
 * All endpoints except /health and /mcp-config require a valid bearer token.
 * The token is read from config.tokenPath at startup (generated by McpAuthManager in Phase 3).
 */
export class McpServer implements IMcpServer {
    private _httpServer: http.Server | undefined;
    private _sdkServer: SdkServer | undefined;
    private readonly _transports = new Map<string, SSEServerTransport>();
    private readonly _tools = new Map<string, IMcpTool>();
    private readonly _prompts = new Map<string, IMcpPrompt>();
    private _running = false;
    private _port = 0;

    constructor(
        private readonly config: McpServerConfig,
        tools: IMcpTool[],
        prompts: IMcpPrompt[] = [],
        private readonly logger: (msg: string) => void = () => { /* no-op */ },
        private readonly getSessionCount: () => number = () => 0,
    ) {
        for (const tool of tools) {
            this._tools.set(tool.name, tool);
        }
        for (const prompt of prompts) {
            this._prompts.set(prompt.name, prompt);
        }
    }

    get isRunning(): boolean { return this._running; }
    get port(): number { return this._port; }

    /** Register an additional tool. Must be called before start(). */
    register(tool: IMcpTool): void {
        this._tools.set(tool.name, tool);
    }

    /** Register an additional prompt. Must be called before start(). */
    registerPrompt(prompt: IMcpPrompt): void {
        this._prompts.set(prompt.name, prompt);
    }

    async start(): Promise<void> {
        if (this._running) { return; }

        if (!this.config.tokenPath) {
            throw new Error('MCP server cannot start: tokenPath is not configured. Set a valid absolute path in McpServerConfig.');
        }
        if (!path.isAbsolute(this.config.tokenPath)) {
            throw new Error(`MCP server cannot start: tokenPath must be an absolute path (got "${this.config.tokenPath}"). Check the extension configuration.`);
        }

        const port = this.config.port;

        // Read bearer token from file (written by McpAuthManager).
        let token: string | undefined;
        try {
            const raw = fs.readFileSync(this.config.tokenPath, 'utf8').trim();
            if (raw) { token = raw; }
        } catch { /* token file not yet created — all protected requests return 503 */ }

        // Low-level SDK server: accepts raw JSON-schema tool definitions.
        const sdkServer = new SdkServer(
            { name: 'chatwizard', version: '1.0.0' },
            { capabilities: { tools: {}, prompts: {} } },
        );

        // List available tools.
        sdkServer.setRequestHandler(ListToolsRequestSchema, async () => ({
            tools: Array.from(this._tools.values()).map(t => ({
                name: t.name,
                description: t.description,
                inputSchema: t.inputSchema as { type: 'object'; properties?: Record<string, object>; required?: string[] },
            })),
        }));

        // Dispatch tool calls; wrap thrown errors so they never become HTTP 500s.
        sdkServer.setRequestHandler(CallToolRequestSchema, async (request) => {
            const toolName = request.params.name;
            this.logger(`[Chat Wizard] MCP tools/call: ${toolName}`);
            const tool = this._tools.get(toolName);
            if (!tool) {
                return {
                    content: [{ type: 'text' as const, text: `Unknown tool: ${toolName}` }],
                    isError: true,
                };
            }
            try {
                return await tool.execute(request.params.arguments ?? {}) as unknown as CallToolResult;
            } catch (err) {
                return {
                    content: [{ type: 'text' as const, text: `Tool execution error: ${String(err)}` }],
                    isError: true,
                } as CallToolResult;
            }
        });

        // List available prompts (slash commands).
        sdkServer.setRequestHandler(ListPromptsRequestSchema, async () => {
            this.logger(`[Chat Wizard] MCP prompts/list: ${this._prompts.size} prompt(s)`);
            return {
                prompts: Array.from(this._prompts.values()).map(p => ({
                    name: p.name,
                    description: p.description,
                    arguments: p.arguments,
                })),
            };
        });

        // Render prompt template to a prompt message.
        sdkServer.setRequestHandler(GetPromptRequestSchema, async (request) => {
            const promptName = request.params.name;
            this.logger(
                `[Chat Wizard] MCP prompts/get: ${promptName} args=${JSON.stringify(request.params.arguments ?? {})}`
            );
            const prompt = this._prompts.get(promptName);
            if (!prompt) {
                throw new Error(`Unknown prompt: ${promptName}`);
            }

            const rendered = await prompt.render(request.params.arguments ?? {});
            const text = rendered.content
                .filter(c => c.type === 'text')
                .map(c => c.text)
                .join('\n\n')
                .trim();

            return {
                description: prompt.description,
                messages: [
                    {
                        role: 'user',
                        content: {
                            type: 'text',
                            text: text || 'No prompt content generated.',
                        },
                    },
                ],
            };
        });

        // Auth middleware — returns false and sends an error response if auth fails.
        const checkAuth = (req: http.IncomingMessage, res: http.ServerResponse): boolean => {
            if (!token) {
                res.writeHead(503, { 'Content-Type': 'application/json' })
                    .end(JSON.stringify({
                        error: 'MCP server token not initialized — the token file was missing or unreadable when the server started. Re-run the \'ChatWizard: Start MCP Server\' command to regenerate the token and restart the server.',
                    }));
                return false;
            }
            const authHeader = req.headers['authorization'] ?? '';
            const supplied = authHeader.startsWith('Bearer ') ? authHeader.slice(7).trim() : '';
            if (supplied !== token) {
                res.writeHead(401, { 'Content-Type': 'application/json' })
                    .end(JSON.stringify({ error: 'Unauthorized: invalid or missing bearer token.' }));
                return false;
            }
            return true;
        };

        await new Promise<void>((resolve, reject) => {
            const httpServer = http.createServer(async (req, res) => {
                try {
                    const urlPath = req.url?.split('?')[0] ?? '';

                    // ── Unauthenticated endpoints ──────────────────────────────
                    if (req.method === 'GET' && urlPath === '/health') {
                        res.writeHead(200, { 'Content-Type': 'application/json' })
                            .end(JSON.stringify({ status: 'ok', sessions: this.getSessionCount() }));
                        return;
                    }

                    if (req.method === 'GET' && urlPath === '/mcp-config') {
                        res.writeHead(200, { 'Content-Type': 'application/json' })
                            .end(this._buildConfigSnippet(port, token));
                        return;
                    }

                    // ── Authenticated endpoints ────────────────────────────────
                    if (!checkAuth(req, res)) { return; }

                    if (req.method === 'GET' && urlPath === '/sse') {
                        const transport = new SSEServerTransport('/messages', res);
                        const sessionId = transport.sessionId;
                        this._transports.set(sessionId, transport);
                        transport.onclose = () => { this._transports.delete(sessionId); };
                        await sdkServer.connect(transport);

                    } else if (req.method === 'POST' && urlPath === '/messages') {
                        const rawQs = req.url?.includes('?')
                            ? req.url.slice(req.url.indexOf('?') + 1)
                            : '';
                        const sessionId = new URLSearchParams(rawQs).get('sessionId') ?? '';
                        const transport = this._transports.get(sessionId);
                        if (transport) {
                            await transport.handlePostMessage(req, res);
                        } else {
                            res.writeHead(404).end('Session not found');
                        }

                    } else {
                        res.writeHead(404).end();
                    }
                } catch (err) {
                    if (!res.headersSent) {
                        res.writeHead(500).end(String(err));
                    }
                }
            });

            httpServer.once('error', (err: NodeJS.ErrnoException) => {
                if (err.code === 'EADDRINUSE') {
                    reject(new Error(
                        `MCP server port ${port} is already in use. ` +
                        `Change the port via the 'chatwizard.mcpServer.port' setting and restart VS Code.`,
                    ));
                } else {
                    reject(err);
                }
            });

            httpServer.listen(port, '127.0.0.1', () => {
                this._httpServer = httpServer;
                this._sdkServer = sdkServer;
                this._port = port;
                this._running = true;
                this.logger(`ChatWizard MCP server started on port ${port}`);
                resolve();
            });
        });
    }

    async stop(): Promise<void> {
        if (!this._running) { return; }

        this._running = false;
        this._port = 0;

        for (const transport of this._transports.values()) {
            try { await transport.close(); } catch { /* ignore */ }
        }
        this._transports.clear();

        await this._sdkServer?.close();
        this._sdkServer = undefined;

        await new Promise<void>((resolve) => {
            if (this._httpServer) {
                this._httpServer.close(() => resolve());
                this._httpServer = undefined;
            } else {
                resolve();
            }
        });

        this.logger('ChatWizard MCP server stopped.');
    }

    dispose(): Promise<void> {
        return this.stop();
    }

    /** Returns a generic JSON config snippet for the /mcp-config endpoint. */
    private _buildConfigSnippet(port: number, token: string | undefined): string {
        const baseUrl = `http://localhost:${port}`;
        const authHeader = token ? `Bearer ${token}` : '<token-not-yet-generated>';
        return JSON.stringify({
            url: baseUrl,
            authorization: authHeader,
            endpoints: {
                sse: `${baseUrl}/sse`,
                messages: `${baseUrl}/messages`,
                health: `${baseUrl}/health`,
            },
            note: 'Use the ChatWizard "Copy MCP Config" command for a tool-specific snippet.',
        }, null, 2);
    }
}
