// src/analytics/kbEngine.ts
// Feature 23 — Shared KB engine: builds classified entries from sessions + sidecar.
// Used by both the dashboard (kbDashboardPanel.ts) and the exporter (extension.ts).

import type { Session, SessionMetadata } from '../types/index';
import type { KbEntry, KbEntryType } from '../types/kb';
import { classifySession, classifySessionWithCategories } from './kbClassifier';
import { classifyTopLevelCategories } from './kbLlmClassifier';

export interface KbEngineResult {
    /** Every session classified as a KB entry. */
    entries: KbEntry[];
    /** Entries grouped by type. */
    grouped: Map<KbEntryType, KbEntry[]>;
    /** Total entry count. */
    total: number;
    /**
     * Optional hierarchical grouping: top-level category → child category labels.
     * Generated by a 2nd LLM pass over all distinct category labels.
     * When null/undefined, the UI shows a flat view.
     */
    topLevelGrouping?: Map<string, string[]> | null;
}

/**
 * Strip common "User [verb]" prefixes from summary text.
 *
 * Examples:
 *   "User requested to continue a chat feature..." → "Continue a chat feature..."
 *   "User is troubleshooting a Copilot ext..."     → "Troubleshooting a Copilot ext..."
 *   "User wants to refactor the module..."         → "Refactor the module..."
 */
export function cleanSummary(summary: string): string {
    return summary.replace(
        /^User\s+(?:requested\s+to|is\s+|wants\s+to|asks?\s+to|asked\s+to)\s*/i,
        '',
    );
}

/**
 * Build KB entries from all sessions and their sidecar metadata.
 *
 * The AI-first pipeline works as follows:
 * 1. Each session is sent to the free AI model (Copilot LM API) which freely
 *    generates a category label based on the conversation content — no predefined
 *    buckets are used.
 * 2. If the AI model is unavailable, the heuristic `classifySession()` fallback
 *    assigns one of the five hardcoded types (decision, learning, pattern, gotcha,
 *    architecture).
 *
 * The `categories` parameter only constrains the HEURISTIC fallback — it defines
 * which types the heuristic is allowed to return. When the LLM succeeds, its
 * free-form label is used regardless of the `categories` list.
 *
 * @param sessions    All hydrated sessions (must have messages loaded).
 * @param cache       Sidecar metadata map (sessionId → SessionMetadata), or null.
 * @param categories  Optional list of categories for the HEURISTIC fallback only.
 *                    When the LLM is available, categories emerge freely from content.
 *                    Defaults to the five built-in types for fallback compatibility.
 */
export async function buildKbEntries(
    sessions: Session[],
    cache: Map<string, SessionMetadata> | null,
    categories?: KbEntryType[],
    onProgress?: (done: number, total: number) => void,
): Promise<KbEngineResult> {
    const entries: KbEntry[] = new Array(sessions.length);
    const grouped = new Map<KbEntryType, KbEntry[]>();

    const useCategories = categories ?? ['decision', 'learning', 'pattern', 'gotcha', 'architecture'];
    let completed = 0;

    await Promise.all(sessions.map(async (session, i) => {
        const meta = cache?.get(session.id);
        const tags = meta?.tags ?? [];
        const entryType = await classifySessionWithCategories(session, useCategories);
        const rawSummary = meta?.summary ?? session.title;
        const summary = cleanSummary(rawSummary);

        entries[i] = {
            sessionId: session.id,
            type: entryType,
            title: session.title,
            summary,
            tags,
            createdAt: session.createdAt,
        };

        completed++;
        onProgress?.(completed, sessions.length);
    }));

    for (const entry of entries) {
        const group = grouped.get(entry.type);
        if (group) {
            group.push(entry);
        } else {
            grouped.set(entry.type, [entry]);
        }
    }

    // ── 2nd pass: group fine-grained categories into top-level buckets ──────
    // Collect all unique category labels and ask the LLM to group them
    // hierarchically. This is best-effort — if the LLM is unavailable or the
    // result can't be parsed, topLevelGrouping stays undefined.
    const allFineCategories = Array.from(new Set(entries.map(e => e.type))).sort();
    const topLevelGrouping = allFineCategories.length > 1
        ? await classifyTopLevelCategories(allFineCategories).catch(() => null)
        : undefined;

    return { entries, grouped, total: entries.length, topLevelGrouping };
}